name: Check Jupyter Notebooks

on:
  push:
    branches:
      - week-1
      - week-2
      - week-3

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: 레포지토리의 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Docker 설정
      - name: Set up Docker
        run: |
          docker build -t notebook-checker .

      # Step 3: Docker 컨테이너에서 노트북 실행
      - name: Run Notebook Tests
        run: |
          docker run --rm notebook-checker bash -c "jupyter nbconvert --to notebook --execute --inplace week-*.ipynb"
      
      # Step 4: 노트북 내 <fill>이 남아있는지 검사
      - name: Check for ##<fill>##
        run: |
          if grep -rn "##<fill>##" week-*.ipynb; then
            echo "노트북에 빈칸이 남아있습니다."
            exit 1
          else
            echo "모든 노트북이 완료되었습니다."
          fi